### ISSUE TITLE
Invoke-DbaQuery - `$null` Handling When `$Err` Defined In Session 

### ISSUE THREAD

**Issue by mattcargile** [dataplat/dbatools#8186]
### Verified issue does not already exist?

Yes

### What error did you receive?

Output from `$error[0] | select *`
```powershell
PSMessageDetails      :
Exception             : System.Exception: You cannot call a method on a null-valued expression.
                         ---> System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                           at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
                           at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                           at System.Management.Automation.CommandProcessor.ProcessRecord()
                           --- End of inner exception stack trace ---
TargetObject          : (localdb)\ProjectsV15
CategoryInfo          : InvalidOperation: ((localdb)\ProjectsV15:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Invoke-DbaQuery,Stop-Function
ErrorDetails          : You cannot call a method on a null-valued expression.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.71\allcommands.ps1: line 93862
                        at Invoke-DbaQuery<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.71\allcommands.ps1: line 49669
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}
```

Output from `$error[0].exception.innerexception.errorrecord | select *`

```powershell
PSMessageDetails      :
Exception             : System.Management.Automation.ParentContainsErrorRecordException: You cannot call a method on a null-valued expression.
TargetObject          :
CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
FullyQualifiedErrorId : InvokeMethodOnNull
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Resolve-SqlError, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.71\allcommands.ps1: line 89447
                        at Invoke-DbaAsync<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.71\allcommands.ps1: line 89638
                        at Invoke-DbaQuery<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.71\allcommands.ps1: line 49666
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

### Steps to Reproduce

```powershell
$err = 'hello world'
Invoke-DbaQuery -SqlInstance localhost -Query 'SELECT 1'
```

### Are you running the latest release?

Yes

### Other details or mentions

Maybe the below line could be moved into the `catch` block above?

https://github.com/dataplat/dbatools/blob/a40fcb08e43952e5e02e3ffb7790315d1d8dcdcc/internal/functions/Invoke-DbaAsync.ps1#L280

Or maybe defining it as `$private:Err`?

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

```powershell

[32;1mName                           Value[0m
[32;1m----                           -----[0m
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### SQL Server Edition and Build number

```sql
Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64) 
	Sep 24 2019 13:48:23 
	Copyright (C) 2019 Microsoft Corporation
	Express Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 18363: ) (Hypervisor)
```

### .NET Framework Version

`.NET 6.0.0-rtm.21522.10`

**Comment by andreasjordan** [comment]
Thanks for the bug report, initialization of $Err was missing. Opened a pull requst for that.
