### ISSUE TITLE
Get-DbaAgHadr has issues if a default instance (non named)

### ISSUE THREAD

**Issue by consciouspnm** [dataplat/dbatools#8380]
### Verified issue does not already exist?

Yes

### What error did you receive?

writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: The network path was not found ---> Microsoft.Data.SqlClient.SqlException: A network-related or instance-specific error occurred while 
                        establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured 
                        to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception: The 
                        network path was not found
                           --- End of inner exception stack trace ---
                           at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
                           at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
                           at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, 
                        Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean withFailover, Boolean isFirstTransparentAttempt, SqlAuthenticationMethod authType, 
                        String certificate, ServerCertificateValidationCallback serverCallback, ClientCertificateRetrievalCallback clientCallback, Boolean useOriginalAddressInfo, Boolean 
                        disableTnir)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean 
                        ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover, Boolean isFirstTransparentAttempt, Boolean disableTnir)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean 
                        redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, 
                        String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, 
                        Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData 
                        reconnectSessionData, ServerCertificateValidationCallback serverCallback, ClientCertificateRetrievalCallback clientCallback, DbConnectionPool pool, String 
                        accessToken, SqlClientOriginalNetworkAddressInfo originalNetworkAddressInfo, Boolean applyTransientFaultHandling)
                           at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, 
                        DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
                           at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, 
                        DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
                           at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
                           at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
                           at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean 
                        onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
                           at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, 
                        DbConnectionInternal& connection)
                           at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, 
                        DbConnectionInternal oldConnection, DbConnectionInternal& connection)
                           at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, 
                        TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                           at Microsoft.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
                           at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
                           at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnectImpl()
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnect()
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
                           --- End of inner exception stack trace ---
TargetObject          : MSSQLSERVER
CategoryInfo          : ConnectionError: (MSSQLSERVER:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Get-DbaAgHadr,Stop-Function
ErrorDetails          : The network path was not found
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.101\allcommands.ps1: line 147825
                        at Get-DbaAgHadr<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.101\allcommands.ps1: line 31001
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

### Steps to Reproduce

Get-DbaAgHadr -SqlInstance MSSQLSERVER

### Are you running the latest release?

Yes

### Other details or mentions

Get-DbaAgHadr -SqlInstance localhost 

produces server name output but still no indication if HADR is installed

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                                         
----                           -----                                                                                                                                                         
PSVersion                      5.1.17763.2867                                                                                                                                                
PSEdition                      Desktop                                                                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                       
BuildVersion                   10.0.17763.2867                                                                                                                                               
CLRVersion                     4.0.30319.42000                                                                                                                                               
WSManStackVersion              3.0                                                                                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                                                                           
SerializationVersion           1.1.0.1                                                                                                                                                       

### SQL Server Edition and Build number

SQL 2019

### .NET Framework Version

.NET Framework 4.8.4510.0

**Comment by consciouspnm** [comment]
MSSQLSERVER is the name of the default, non named instance, so SSMS connects with just the server name. I’ll try your query when I get in tomorrow but I tried local host and the server name and while they didn’t error as dns resolved them, the output didn’t seem correct. I.e didn’t have any reference to hadr

**Comment by potatoqualitee** [comment]
> MSSQLSERVER is the name of the default, non named instance, so SSMS connects with just the server name.

Correct, in dbatools as well. For instance, this is not valid:

![image](https://user-images.githubusercontent.com/8278033/171340342-2071e2e4-db32-468d-a6aa-0bc7d3a2ee51.png)

When you type `Get-DbaAgHadr -SqlInstance MSSQLSERVER` that's essentially what you are doing.

localhost may work, depending on your certificate setup. it doesn't on my machine, for instance. here's the output you should see:

![image](https://user-images.githubusercontent.com/8278033/171340604-e5ed73d0-a318-4a48-b7b8-a1d7d855bf7a.png)

**Comment by consciouspnm** [comment]
There are inconsistencies in the instance naming between commands
If I install sql with `$Result = Install-Dbainstance -Version 2019 -Path $SQLMedia -InstanceName $SQLInstance `

then if $SQLInstance is the server name (SERVERA) I get an instance called SERVERA\SERVERA, If $SQLInstance is MSSQLSERVER I get a default instance so can connect via SSMS to just the server name.  In SQL Config Manager the Service Name is still:
![image](https://user-images.githubusercontent.com/34806724/171378531-cc9008b2-6e45-49b8-9ccc-566b8839301f.png)

Running Get-DbaAgHadr I get:
![image](https://user-images.githubusercontent.com/34806724/171378905-54576103-04cb-47c4-a9c4-afc77196b4fc.png)
or
![image](https://user-images.githubusercontent.com/34806724/171378996-cc53eb26-8f0b-4da9-a51b-ae4d7cfd7b34.png)

Which doesn't match your output.

If you look at the source code for the Enable, Disable and Get, the first two use a different method to do the checks and I would have thought that Get would have used the same method.

Enable gives these results:
![image](https://user-images.githubusercontent.com/34806724/171379856-a8e6a1ab-f18c-40ed-9673-30c274a4a3fc.png)
or
![image](https://user-images.githubusercontent.com/34806724/171380017-419e6ae9-7cbf-416d-9a1f-a972148fb94d.png)

So does seem to work using either name.

**Comment by potatoqualitee** [comment]
Thank you. It can be confusing, but a default instance is indeed called `MSSQLSERVER` under the hood. We generally don't need to care about that detail and we just call the machine by its hostname when trying to connect. For example, `server01` or `server02`. SQL Server will respond on port 1433 when it's a default instance.

A named instance is when a SQL Server instance is installed with a specific name like `SQLEXPRESS`. The way we'd connect is `server01\SQLEXPRESS` or `server02\SQLEXPRESS`. The port is randomly chosen and the SQL Server Browser Service helps clients detect which port they should try on.

This is an example of what it looks like when the instance is installed as a named instance.

![image](https://user-images.githubusercontent.com/8278033/171403091-dd92bffa-6558-4dc5-a698-6b8b5d5764f2.png)

Something appears wrong with your PowerShell session, which isn't uncommon with the ISE. You should only be seeing a subset of the output of `Connect-DbaInstance`, but you're seeing the default output. I am unable to determine if you're still using the ISE or powershell.exe. Please close out all of your PowerShell windows, reopen and try it again.

The reason Get is different from Enable/Disable is because Enable/Disable are required to interact with SQLWMI which can be a bit intense as it requires admin permissions when run locally. SQLQMI is also what powers the SQL Server Configuration Manager. Get can gather what it needs from a simple SMO connection, and we prefer using that when we can, over SQLWMI.
