### ISSUE TITLE
Connect-DbaInstance Fails With SQL Server 2000 when using PowerShell 7

### ISSUE THREAD

**Issue by RandyInMarin** [dataplat/dbatools#8425]
### Verified issue does not already exist?

Yes

### What error did you receive?

DEBUG: 5210 | [13:46:58][Connect-DbaInstance] We connect to the instance by running SELECT 'dbatools is opening a new connection'
DEBUG: [13:46:58][Connect-DbaInstance] Failure | Error connecting to [xxxxxxxx]: Internal connection fatal error.
ConnectionError: C:\Users\x\Documents\PowerShell\Modules\dbatools\1.1.110\allcommands.ps1:147838:9
  Line |
147838 |          throw $records[0]
       |          ~~~~~~~~~~~~~~~~~
       | Error connecting to [xxxxxxxx]: Internal connection fatal error.

### Steps to Reproduce

Note: The source is an old server with SQL Server 2000
Note: Use PowerShell 7

Connect-DbaInstance -SqlInstance $source -Verbose -Debug

### Are you running the latest release?

Yes

### Other details or mentions

This is only an issue in PowerShell 7.  It works in PowerShell 5.1.  It appears that .Net Core no longer supports the TDS used by SQL Server 2000.  There might be nothing to fix this.  However, some sort of incompatibility warning should be added that suggests using PowerShell 5.1 until the server is upgraded.  

PS We are using Copy-DbaDatabase to migrate the database, but we must use an older PowerShell for it to work.

### What PowerShell host was used when producing this error

VS Code (integrated terminal)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server  2000 - 8.00.2066 (Intel X86)   May 11 2012 18:41:14   Copyright (c) 1988-2003 Microsoft Corporation  Standard Edition on Windows NT 5.2 (Build 3790: Service Pack 2) 

### .NET Framework Version

.NET 6.0.6

**Comment by andreasjordan** [comment]
The problem is: As we can't connect to the instance, we don't know if it is version 2000.

We do our best to still support way-out-of-support-versions of SQL Server, but I would vote for "wontfix" for this one.

**Comment by andreasjordan** [comment]
But thanks for reporting - maybe someone else has the same problem in the future and finds this issue here.

**Comment by potatoqualitee** [comment]
Can repro, but also agree that there's nothing we can really do about it and also can't know if sql2000 is the target instance to warn. Perhaps we can Check the exception for TdsParser and guess they are on sql2000. Is that the sort of solution you're asking for? 

```
[1s] C:/github❯ Connect-DbaInstance sql2000
ConnectionError: C:\github\dbatools\internal\functions\flowcontrol\Stop-Function.ps1:253
Line |
 253 |          throw $records[0]
     |          ~~~~~~~~~~~~~~~~~
     | Error connecting to [sql2000]: Internal connection fatal error.

[899ms] C:/github❯ Get-DbatoolsError

CategoryInfo          : ConnectionError: (sql2000:String) [], Exception
ErrorDetails          :
Exception             : System.Exception: Error connecting to [sql2000]: Internal connection fatal
                        error.
                         ---> System.Management.Automation.MethodInvocationException: Exception calling
                        "ExecuteWithResults" with "1" argument(s): "Failed to connect to server
                        sql2000."
                         ---> Microsoft.SqlServer.Management.Common.ConnectionFailureException: Failed
                        to connect to server sql2000.
                         ---> System.InvalidOperationException: Internal connection fatal error.
                           at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior,
                        SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet
                        bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
                           at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior,
                        SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet
                        bulkCopyHandler, TdsParserStateObject stateObj)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean
                        enlistOK)
                           at
                        Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo
                        serverInfo, String newPassword, SecureString newSecurePassword, Boolean
                        ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
                           at
                        Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo
                        serverInfo, String newPassword, SecureString newSecurePassword, Boolean
                        redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential
                        credential, TimeoutTimer timeout)
                           at
                        Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer
                        timeout, SqlConnectionString connectionOptions, SqlCredential credential,
                        String newPassword, SecureString newSecurePassword, Boolean
                        redirectedUserInstance)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolId
                        entity identity, SqlConnectionString connectionOptions, SqlCredential
                        credential, Object providerInfo, String newPassword, SecureString
                        newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString
                        userConnectionOptions, SessionData reconnectSessionData, Boolean
                        applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
                           at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectio
                        nOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo,
                        DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions
                        userOptions)
                           at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbC
                        onnectionPool pool, DbConnection owningObject, DbConnectionOptions options,
                        DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
                           at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection
                        owningObject, DbConnectionOptions userOptions, DbConnectionInternal
                        oldConnection)
                           at
                        Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection
                        owningObject, DbConnectionOptions userOptions, DbConnectionInternal
                        oldConnection)
                           at
                        Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection
                        owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate,
                        Boolean onlyOneCheckConnection, DbConnectionOptions userOptions,
                        DbConnectionInternal& connection)
                           at
                        Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection
                        owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions,
                        DbConnectionInternal& connection)
                           at
                        Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection
                        owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions
                        userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&
                        connection)
                           at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal
                        (DbConnection outerConnection, DbConnectionFactory connectionFactory,
                        TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                           at
                        Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection
                        outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1
                        retry, DbConnectionOptions userOptions)
                           at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1
                        retry, SqlConnectionOverrides overrides)
                           at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides
                        overrides)
                           at Microsoft.Data.SqlClient.SqlConnection.Open()
                           at
                        Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnectImpl()
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnect()
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
                           --- End of inner exception stack trace ---
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.PoolConnect()
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(
                        String sqlCommand, Boolean retry)
                           at CallSite.Target(Closure , CallSite , Object , String )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(Fu
                        nctionContext funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(Inter
                        pretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.R
                        un(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.R
                        un(InterpretedFrame frame)
                           --- End of inner exception stack trace ---
FullyQualifiedErrorId : dbatools_Connect-DbaInstance
InvocationInfo        : System.Management.Automation.InvocationInfo
PipelineIterationInfo : {}
PSMessageDetails      :
ScriptStackTrace      : at Stop-Function,
                        C:\github\dbatools\internal\functions\flowcontrol\Stop-Function.ps1: line 253
                        at Connect-DbaInstance<Process>,
                        C:\github\dbatools\functions\Connect-DbaInstance.ps1: line 923
                        at <ScriptBlock>, <No file>: line 1
TargetObject          : sql2000
```

**Comment by drstonephd** [comment]
I don't know how much effort should be put into SQL 2000 compatibility.  Perhaps it's enough to state that SQL Server 2000 is only supported in Windows PowerShell.  

For an error message, I think it would help to let us know that it might be a SQL 2000 compatibility issue.  We migrated our SQL 2000 server last Friday using DBATools via Windows PowerShell.  DBATools made it easy.  The hardest part was figuring out to run it in Windows PowerShell.  Fingers cross the security team does not find another old server.  

The following link hints that ODBC and OleDbConnection are options.  Perhaps retry the connection using ODBC when a TDS issue is detected to verify that this is the issue?  

https://stackoverflow.com/questions/45412345/the-sql-server-instance-returned-an-invalid-or-unsupported-protocol-version-duri

**Comment by potatoqualitee** [comment]
Hmmm @andreasjordan what do you think? I know we need an SMO Server connection but can we build it with `OdbcConnection("Driver={SQL Server};Server=<YOUR_SERVER>;Database=<YOUR_DB>;Trusted_Connection=True;"))` ? Probably not.

**Comment by andreasjordan** [comment]
I think if PowerShell 5.1 works, the users who still need to connect to version 2000 should use this. I would not take the risk of implementing some stuff to still support version 2000 from PowerShell 7 - as we can not test it automated.

**Comment by potatoqualitee** [comment]
agreed, thank you
