### ISSUE TITLE
Export-DbaInstance -SqlInstance -Path ERROR

### ISSUE THREAD

**Issue by Starover27** [dataplat/dbatools#8686]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

WARNING: [10:35:48][Get-DbaRepServer] This command is not yet supported in PowerShell Core
WARNING: [10:36:12][Export-DbaScript] Failure on db-mssql-etc | System.Management.Automation.MethodInvocationException: Exception calling "EnumScript" with "1" argument(s): "The StoredProcedure '[dbo].[PS_MOVE]' cannot be scripted as its data is not accessible."
 ---> Microsoft.SqlServer.Management.Smo.FailedOperationException: The StoredProcedure '[dbo].[PS_MOVE]' cannot be scripted as its data is not accessible.
 ---> Microsoft.SqlServer.Management.Smo.PropertyCannotBeRetrievedException: Property TextHeader is not available for StoredProcedure '[dbo].[PS_MOVE]'. This property may not exist for this object, or may not be retrievable due to insufficient access rights. The text is encrypted.
   at Microsoft.SqlServer.Management.Smo.ScriptNameObjectBase.GetTextProperty(String requestingProperty, ScriptingPreferences sp, Boolean bThrowIfCreating)
   at Microsoft.SqlServer.Management.Smo.ScriptNameObjectBase.GetTextProperty(String requestingProperty, ScriptingPreferences sp)
   at Microsoft.SqlServer.Management.Smo.ScriptNameObjectBase.BuildText(ScriptingPreferences sp)
   at Microsoft.SqlServer.Management.Smo.ScriptNameObjectBase.GetTextForScript(ScriptingPreferences sp, String[] expectedObjectTypes, Boolean forceCheckNameAndManipulateIfRequired, ScriptHeaderType scriptHeaderType)
   at Microsoft.SqlServer.Management.Smo.StoredProcedure.ScriptInternal(StringCollection queries, ScriptingPreferences sp, ScriptHeaderType scriptHeaderType, Boolean skipSetOptions)
   at Microsoft.SqlServer.Management.Smo.StoredProcedure.ScriptSP(StringCollection queries, ScriptingPreferences sp, ScriptHeaderType scriptHeaderType, Boolean skipSetOptions)
   at Microsoft.SqlServer.Management.Smo.StoredProcedure.ScriptCreate(StringCollection queries, ScriptingPreferences sp)   at Microsoft.SqlServer.Management.Smo.StoredProcedure.ScriptCreateInternal(StringCollection query, ScriptingPreferences sp, Boolean skipPropagateScript)
   at Microsoft.SqlServer.Management.Smo.ScriptMaker.ScriptCreateObject(Urn urn, ScriptingPreferences sp, ObjectScriptingType& scriptType)
   at Microsoft.SqlServer.Management.Smo.ScriptMaker.ScriptCreate(Urn urn, ScriptingPreferences sp, ObjectScriptingType& scriptType)
   at Microsoft.SqlServer.Management.Smo.ScriptMaker.ScriptCreateObjects(IEnumerable`1 urns)
   at Microsoft.SqlServer.Management.Smo.ScriptMaker.ScriptUrns(List`1 orderedUrns)
   at Microsoft.SqlServer.Management.Smo.ScriptMaker.DiscoverOrderScript(IEnumerable`1 urns)
   at Microsoft.SqlServer.Management.Smo.ScriptMaker.ScriptWorker(List`1 urns, ISmoScriptWriter writer)
   at Microsoft.SqlServer.Management.Smo.Scripter.ScriptWithListWorker(DependencyCollection depList, SqlSmoObject[] objects, Boolean discoveryRequired)
   at Microsoft.SqlServer.Management.Smo.Scripter.ScriptWithList(DependencyCollection depList, SqlSmoObject[] objects, Boolean discoveryRequired)
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Management.Smo.Scripter.ScriptWithList(DependencyCollection depList, SqlSmoObject[] objects, Boolean discoveryRequired)
   at Microsoft.SqlServer.Management.Smo.Scripter.Script(Urn[] urns, SqlSmoObject[] objects)
   at CallSite.Target(Closure , CallSite , Object , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at Export-DbaScript<Process>(Closure , FunctionContext )

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
 Export-DbaInstance -SqlInstance db-mssql -Path d:\temp

### Please confirm that you are running the most recent version of dbatools

new

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

5

### SQL Server Edition and Build number

2016

### .NET Framework Version

4

**Comment by wsmelton** [comment]
Please also reconfirm what version of dbatools you are using and the PowerShell host.

Your output shows this message which does not exist in the latest release of the module, and only gets spit out if you are using PowerShell 7+:

> WARNING: [10:35:48][Get-DbaRepServer] This command is not yet supported in PowerShell Core

**Comment by wsmelton** [comment]
Closing for now. If OP responds or if still experiencing issues, please submit [a discussion](https://github.com/dataplat/dbatools/discussions) to work through environmental troubleshooting.
