### ISSUE TITLE
Test-DbaBuild throws index error passing in Build string from Get-DbaService

### ISSUE THREAD

**Issue by wsmelton** [dataplat/dbatools#8915]
### Verified issue does not already exist?

No, I did not search

### What error did you receive?

![image](https://github.com/dataplat/dbatools/assets/11204251/e069004e-874c-4425-a5bc-6379f9d30f85)

```console
InvalidOperation: C:\git\dataplat\dbatools\public\Test-DbaBuild.ps1:235
Line |
 235 |  …                  $targetedBuild = $IdxVersion[$IdxVersion.Length - 1]
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot index into a null array.
```

`Get-Error` output
```console
Exception             : 
    Type        : System.Management.Automation.RuntimeException
    ErrorRecord : 
        Exception             : 
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot index into a null array.
            HResult : -2146233087
        CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : NullArray
        InvocationInfo        : 
            ScriptLineNumber : 235
            OffsetInLine     : 21
            HistoryId        : -1
            ScriptName       : C:\git\dataplat\dbatools\public\Test-DbaBuild.ps1
            Line             : $targetedBuild = $IdxVersion[$IdxVersion.Length - 1]
                               
            PositionMessage  : At C:\git\dataplat\dbatools\public\Test-DbaBuild.ps1:235 char:21
                               + ΓÇª                  $targetedBuild = $IdxVersion[$IdxVersion.Length - 1]
                               +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            PSScriptRoot     : C:\git\dataplat\dbatools\public
            PSCommandPath    : C:\git\dataplat\dbatools\public\Test-DbaBuild.ps1
            CommandOrigin    : Internal
        ScriptStackTrace      : at Test-DbaBuild<Process>, C:\git\dataplat\dbatools\public\Test-DbaBuild.ps1: line 235
                                at <ScriptBlock>, <No file>: line 1
    TargetSite  : System.Object CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object, System.Object)
    Message     : Cannot index into a null array.
    Data        : System.Collections.ListDictionaryInternal
    Source      : Anonymously Hosted DynamicMethods Assembly
    HResult     : -2146233087
    StackTrace  : 
   at CallSite.Target(Closure, CallSite, Object, Object)
   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : InvalidOperation: (:) [], RuntimeException
FullyQualifiedErrorId : NullArray
InvocationInfo        : 
    ScriptLineNumber : 235
    OffsetInLine     : 21
    HistoryId        : -1
    ScriptName       : C:\git\dataplat\dbatools\public\Test-DbaBuild.ps1
    Line             : $targetedBuild = $IdxVersion[$IdxVersion.Length - 1]
                       
    PositionMessage  : At C:\git\dataplat\dbatools\public\Test-DbaBuild.ps1:235 char:21
                       + ΓÇª                  $targetedBuild = $IdxVersion[$IdxVersion.Length - 1]
                       +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\git\dataplat\dbatools\public
    PSCommandPath    : C:\git\dataplat\dbatools\public\Test-DbaBuild.ps1
    CommandOrigin    : Internal
ScriptStackTrace      : at Test-DbaBuild<Process>, C:\git\dataplat\dbatools\public\Test-DbaBuild.ps1: line 235
                        at <ScriptBlock>, <No file>: line 1

```

### Steps to Reproduce

```powershell
$data = Get-DbaService ...
Test-DbaBuild -Build $data.Version -Latest
#or
Test-DbaBuild -Build $data.Version -Latest -Update
```

### Please confirm that you are running the most recent version of dbatools

Development branch

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

```
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### SQL Server Edition and Build number

N/A

### .NET Framework Version

N/A

**Comment by wsmelton** [comment]
Even if I pass in a string that is formatted properly it still throws the same error now

![image](https://github.com/dataplat/dbatools/assets/11204251/73cf3157-bdd2-4061-b8ed-8e63ad8f88f8)

**Comment by andreasjordan** [comment]
But it works for a "correct" Version, that is found in the json file:

![image](https://github.com/dataplat/dbatools/assets/66946165/718f1344-d128-43ac-8401-d6c8b0e2e9e8)

So we would have to improve the error handling...

**Comment by andreasjordan** [comment]
If someone is doing a refactoring, please have a look at `$IdxRef`...

**Comment by andreasjordan** [comment]
And now I realized that "13.3.6300" is a valid build as it is an "alias" for "13.0.6300" which we have in the json file.

We use this code in `Get-SQLInstanceComponent`:
```
                # Replace first decimal of the minor build with a 0, since we're using build numbers here
                # Refer to https://sqlserverbuilds.blogspot.com/
                Write-Message -Level Debug -Message "Converting version $($result.Version) to [version]"
                $newVersion = New-Object -TypeName System.Version -ArgumentList ([string]$result.Version)
                $newVersion = New-Object -TypeName System.Version -ArgumentList ($newVersion.Major , ($newVersion.Minor - $newVersion.Minor % 10), $newVersion.Build)
                Write-Message -Level Debug -Message "Converted version $($result.Version) to $newVersion"
```

Should we use this code in `Get-DbaBuild` and/or `Test-DbaBuild` as well?

**Comment by andreasjordan** [comment]
@niphlod - Can you have a look at this issue? Thanks.

**Comment by andreasjordan** [comment]
Thanks for the solution, looks good.
