### ISSUE TITLE
Copy-DbaDatabase without Source parameter and no pipe input raises error message

### ISSUE THREAD

**Issue by mikeblas** [dataplat/dbatools#9001]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

```
writeErrorStream      : True
PSMessageDetails      :
Exception             : System.Exception: Cannot bind argument to parameter 'SqlInstance' because it is null. ---> System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter
                        'SqlInstance' because it is null.
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           --- End of inner exception stack trace ---
TargetObject          :
CategoryInfo          : InvalidData: (:) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Copy-DbaDatabase,Stop-Function
ErrorDetails          : Cannot bind argument to parameter 'SqlInstance' because it is null.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, <No file>: line 151389
                        at Copy-DbaDatabase<Process>, <No file>: line 9385
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}
```

### Steps to Reproduce

```powershell
copy-dbadatabase -destination slide -database junk -detachattach -newname junk33
```

### Please confirm that you are running the most recent version of dbatools

2.0.4

### Other details or mentions

Invoking copy-dbadatabase without -source parameter like this: 

```powershell
copy-dbadatabase -destination slide -database junk -detachattach -newname junk33
```
causes:

```
WARNING: [08:20:27][Copy-DbaDatabase] Failure | Cannot bind argument to parameter 'SqlInstance' because it is null.
```

This is a warning, even though it fatally stops the script. Further, the `SqlInstance` parameter describes an internal parameter being incorrect  rather than anything the user has directly [not] specified.

The `$Source` parameter can't be mandatory -- it's optional, since there might be piped input delivering the source server and a list of databases. Either piped input must be provided or the -Source parameter must be given. Otherwise, the source is unknown. The parameter checking at the head of the script is inadequate as it doesn't test for the combined lack of an input pipe and the failure to provide a `-Source` parameter. While this condition (like any other parameter issue) is user error, the message given isn't helpful for diagnosing the problem.

See also https://github.com/dataplat/web/issues/39

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

```
Name                           Value                                                                                                                                                                                          
----                           -----                                                                                                                                                                                          
PSVersion                      5.1.17763.3770                                                                                                                                                                                 
PSEdition                      Desktop                                                                                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                        
BuildVersion                   10.0.17763.3770                                                                                                                                                                                
CLRVersion                     4.0.30319.42000                                                                                                                                                                                
WSManStackVersion              3.0                                                                                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                                                                                            
SerializationVersion           1.1.0.1                                                                                                                                                                                        

```

### SQL Server Edition and Build number

```
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Microsoft SQL Server 2022 (RTM-GDR) (KB5021522) - 16.0.1050.5 (X64) 
	Jan 23 2023 17:02:42 
	Copyright (C) 2022 Microsoft Corporation
	Developer Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: )
```

### .NET Framework Version

```
PSChildName Version
----------- -------
Client      4.7.03190
Full        4.7.03190
Client      4.0.0.0

```

**Comment by wsmelton** [comment]
It's a warning by design. We don't output error messages, if you want that you need provide `-EnableException` as the parameter description states.
