### ISSUE TITLE
Rename-DbaDatabase Produces an error when ReplaceBefore is specified

### ISSUE THREAD

**Issue by Swetz-Empigo** [dataplat/dbatools#9069]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

PSMessageDetails      : 
Exception             : System.Management.Automation.MethodException: Cannot convert argument "newChar", with value: "", for "Replace" to type 
                        "System.Char": "Cannot convert value "" to type "System.Char". Error: "String must be exactly one character long."" ---> 
                        System.Management.Automation.PSInvalidCastException: Cannot convert value "" to type "System.Char". Error: "String must 
                        be exactly one character long." ---> System.FormatException: String must be exactly one character long.
                           at System.Char.Parse(String s)
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.LanguagePrimitives.ConvertViaParseMethod.ConvertWithoutCulture(Object valueToConvert, 
                        Type resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable 
                        backupTable)
                           at CallSite.Target(Closure , CallSite , Object , Object , String )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.ConvertToArgumentConversionException(Exception exception, String 
                        parameterName, Object argument, String method, Type toType)
                           at CallSite.Target(Closure , CallSite , Object , Object , String )
                           at System.Management.Automation.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], MethodException
FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Rename-DbaDatabase<Process>, <No file>: line 109014
                        at <ScriptBlock>, <No file>: line 3
PipelineIterationInfo : {}

### Steps to Reproduce

Create a database with 3 files, including a separate index file group and data file.

`USE [master]
GO

/****** Object:  Database [TestName]    Script Date: 9/1/2023 8:43:08 AM ******/
CREATE DATABASE [TestName]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TestName', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQL2019DEVELOPER\MSSQL\Data\TestName.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ), 
 FILEGROUP [Index] 
( NAME = N'TestName_Index', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQL2019DEVELOPER\MSSQL\Data\TestName_idx.ndf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TestName_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQL2019DEVELOPER\MSSQL\Data\TestName_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TestName].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TestName] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TestName] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TestName] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TestName] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TestName] SET ARITHABORT OFF 
GO

ALTER DATABASE [TestName] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TestName] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TestName] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TestName] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TestName] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TestName] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TestName] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TestName] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TestName] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TestName] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TestName] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TestName] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TestName] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TestName] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TestName] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TestName] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TestName] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TestName] SET RECOVERY FULL 
GO

ALTER DATABASE [TestName] SET  MULTI_USER 
GO

ALTER DATABASE [TestName] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TestName] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TestName] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TestName] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TestName] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TestName] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TestName] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TestName] SET  READ_WRITE 
GO

`

Call Rename-DbaDatabase command as follows.

`Rename-DbaDatabase -SqlInstance "SQL2019DEVELOPER" -Database TestName -DatabaseName "TestName_20230901" -LogicalName "<DBN><LGN>" -FileName "<DBN><FNN>" -ReplaceBefore -Preview;`

Expected behavior would be the following attempted rename:

Database Name: TestName -> TestName_20230901

Logical Names:
TestName -> TestName_20230901
TestName_Index -> TestName_20230901_Index
TestName_Log -> TestName_20230901_Log

Physical File Names

C:\Program Files\Microsoft SQL Server\MSSQL15.SQL2019DEVELOPER\MSSQL\Data\TestName.mdf -> C:\Program Files\Microsoft SQL Server\MSSQL15.SQL2019DEVELOPER\MSSQL\Data\TestName_20230901.mdf

C:\Program Files\Microsoft SQL Server\MSSQL15.SQL2019DEVELOPER\MSSQL\Data\TestName_idx.ndf -> C:\Program Files\Microsoft SQL Server\MSSQL15.SQL2019DEVELOPER\MSSQL\Data\TestName_20230901_idx.ndf

C:\Program Files\Microsoft SQL Server\MSSQL15.SQL2019DEVELOPER\MSSQL\Data\TestName_log.ldf -> C:\Program Files\Microsoft SQL Server\MSSQL15.SQL2019DEVELOPER\MSSQL\Data\TestName_20230901_log.ldf

### Please confirm that you are running the most recent version of dbatools

2.0.4

### Other details or mentions

I found this closed bug that appears to report the same issue: [https://github.com/dataplat/dbatools/issues/3677](url)

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                                                             
----                           -----                                                                                                             
PSVersion                      5.1.19041.3031                                                                                                    
PSEdition                      Desktop                                                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                           
BuildVersion                   10.0.19041.3031                                                                                                   
CLRVersion                     4.0.30319.42000                                                                                                   
WSManStackVersion              3.0                                                                                                               
PSRemotingProtocolVersion      2.3                                                                                                               
SerializationVersion           1.1.0.1                                                                                                           

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-GDR) (KB5021125) - 15.0.2101.7 (X64)   Jan 23 2023 13:08:05   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Home 10.0 <X64> (Build 19045: ) 

### .NET Framework Version

.NET Framework 4.8.9167.0

**Comment by potatoqualitee** [comment]
@claude please figure out what is going wrong, fix it and add a regression test then create a PR

**Comment by potatoqualitee** [comment]
@Swetz-Empigo thank you for the report 🙏🏼
