### ISSUE TITLE
Invoke-DbaDbDataMasking and Write-PSFMessage errors

### ISSUE THREAD

**Issue by SQLGB** [dataplat/dbatools#9116]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

```
PS C:\WINDOWS\system32> $error[0] | select *

PSMessageDetails      : 
Exception             : System.Management.Automation.CommandNotFoundException: The term 'Write-PSFMessage' is not recognized as the name of a cmdlet, function, script file, or operable program. 
                        Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
                           at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, 
                        CommandOrigin commandOrigin, ExecutionContext context)
                           at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
                           at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
                           at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, 
                        CommandRedirection[] redirections, ExecutionContext context)
                           at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, 
                        CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : Write-PSFMessage
CategoryInfo          : ObjectNotFound: (Write-PSFMessage:String) [], CommandNotFoundException
FullyQualifiedErrorId : CommandNotFoundException
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Invoke-DbaDbDataMasking<Process>, <No file>: line 75480
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

### Steps to Reproduce

```
Invoke-DbaDbDataMasking -SqlInstance MySqlInstance -Database MyDatabase -Path MyPath -Confirm:$false
```

Run the command when using a mask config file in which "HasUniqueIndex" is set to "true".

### Please confirm that you are running the most recent version of dbatools

2.1.2

### Other details or mentions

Looking at the code for Invoke-DbaDbDataMasking, there are 4 occurrences of "Write-PSFMessage" and 27 occurrences of "Write-Message".  Wondering if those 4 "Write-PSFMessage" should be changed to "Write-Message".

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

```
Name                           Value                                                                                                                                                                  
----                           -----                                                                                                                                                                  
PSVersion                      5.1.17763.4840                                                                                                                                                         
PSEdition                      Desktop                                                                                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                
BuildVersion                   10.0.17763.4840                                                                                                                                                        
CLRVersion                     4.0.30319.42000                                                                                                                                                        
WSManStackVersion              3.0                                                                                                                                                                    
PSRemotingProtocolVersion      2.3                                                                                                                                                                    
SerializationVersion           1.1.0.1                                                                                                                                                                
```

### SQL Server Edition and Build number

Microsoft SQL Server 2022 (RTM-CU8) (KB5029666) - 16.0.4075.1 (X64)   Aug 23 2023 14:04:50   Copyright (C) 2022 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2022 Datacenter 10.0 <X64> (Build 20348: ) (Hypervisor) 

### .NET Framework Version

.NET Framework 4.7.4051.0

**Comment by andreasjordan** [comment]
Thanks for reporting this - you are absolutly right. I'll open a pull request tpo fix this in a minute.
