### ISSUE TITLE
Export-DbaScript -FilePath parameter Access to path is denied

### ISSUE THREAD

**Issue by davesbrown** [dataplat/dbatools#9136]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

WARNING: [14:07:28][Export-DbaScript] Failure on MyServer | System.UnauthorizedAccessException: Access to the path 'mypath.sqll' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.Management.Automation.PathUtils.MasterStreamOpen(PSCmdlet cmdlet, String filePath, Encoding resolvedEncoding, Boolean defaultEncoding, Boolean Append, Boolean Force, Boolean NoClobber, FileStream& fileStream, StreamWriter& streamWriter, FileInfo& readOnlyFileInfo, Boolean isLiteralPath)

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference

Get-DbaAgentJob -SqlInstance $SqlInstance -Database $Database | Export-DbaScript -FilePath $FilePath -NoPrefix -Append

```

### Please confirm that you are running the most recent version of dbatools

2.1.4Get

### Other details or mentions

-Path works, but only to the directory, was hoping for the explicit file name using -FilePath

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

7.3.4

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU16-GDR) (KB5014353) - 15.0.4236.7 (X64)   May 29 2022 15:55:47   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 

### .NET Framework Version

4.7.03190

**Comment by andreasjordan** [comment]
I can not reproduce the issue:
![image](https://github.com/dataplat/dbatools/assets/66946165/b4d040b3-d6d7-400b-9daf-d230c11054ff)

Can you tell me more about the environment you are running this?

**Comment by andreasjordan** [comment]
The target directory must exist. Is that maybe your problem?

**Comment by davesbrown** [comment]
Yes, probably operator error, it seems to be working now.  I may have been thinking of the existence of the filepath on the sqlserver itself, rather than locally where I was running the scripts.  Thanks
